### ISSUE TITLE
Issue with Dynamic Labels

### ISSUE THREAD

**Issue by rakeshgirase** [PeterStaev/NativeScript-Grid-View#37]
Hello All,

I am using nativescript-grid-view for dynamic grid view. The label is
XML View:
`<GridLayout class="margin"> <gv:GridView items="{{ items }}" colWidth="24%" rowHeight="15%" padding="5" itemTap="gridViewItemTap" itemLoading="gridViewItemLoading" loadMoreItems="gridViewLoadMoreItems"> <gv:GridView.itemTemplate> <GridLayout class="{{ status == 'skipped'? 'skipped': status == 'tbd'? 'tbd': 'all' }}" style="margin: 5; border-radius: 50"> <Label text="{{ 'I ' + value }}" class="{{ status == 'skipped'? 'skipped': status == 'tbd'? 'tbd': 'all' }}" style="font-size: 15" verticalAlignment="center" horizontalAlignment="center"/> </GridLayout> </gv:GridView.itemTemplate> </gv:GridView> </GridLayout>`

TS File:
`public items = new ObservableArray();
constructor(){
for (let loop = 0; loop < 65; loop++) {
this.items.push({value: (loop + 1), status: status});
}
}`

Some of the labels in this some grids is displayed partially. This happens only when the label is populated dynamically and not when I use a hardcoded value. Not sure what is going wrong. I have also created a thread on [Nativescript Grid View Issue With Dynamic Labels.](https://discourse.nativescript.org/t/nativescript-grid-view-issue-with-dynamic-labels/4686). You can find the screenshot here. Please advise.

Thanks
Rakesh

**Comment by PeterStaev** [comment]
Hey @rakeshgirase , I'm having a similar problem with the built-in `ListView` component. From what I've seen the issue is that when you have `auto` column and the component reuses the item view, it does not do a resize of the views. So If you have some label that contains only one character, and then this view is reused for an item which label has to have 2 characters it still uses the size of the original item so the text is clipped. In your case you can avoid this by changing your grid to use a `*` column and stretching the label inside. Then centering the text inside the label (instead of centering the label itself like you are doing it now). 

So your XML should look something like:
```xml
<gv:GridView items="{{ items }}" colWidth="24%" rowHeight="15%" padding="5" itemTap="gridViewItemTap" itemLoading="gridViewItemLoading" loadMoreItems="gridViewLoadMoreItems">
    <gv:GridView.itemTemplate>
        <GridLayout columns="*" class="{{ status == 'skipped'? 'skipped': status == 'tbd'? 'tbd': 'all' }}" style="margin: 5; border-radius: 50"> 
            <Label text="{{ 'I ' + value }}" class="{{ status == 'skipped'? 'skipped': status == 'tbd'? 'tbd': 'all' }}" style="font-size: 15;text-align: center" verticalAlignment="center" horizontalAlignment="stretch"/> 
        </GridLayout> 
    </gv:GridView.itemTemplate> 
</gv:GridView>
```

**Comment by rakeshgirase** [comment]
Thank You @PeterStaev
