### ISSUE TITLE
Any Forks of this?

### ISSUE THREAD

**Issue by razorsyntax** [PeterStaev/NativeScript-Grid-View#62]
I'm definitely not supporting ProPlugins.  I'm grateful for all the work that went into this, but as an individual dev, you've priced me and others like me out of the game.

Is there an alternative to the gridview plugin that supports Nativescript 6+?

**Comment by PeterStaev** [comment]
@razorsyntax , you can try the `RadListView` as far as I know it has similar functions like this plugin. 

Or you can see to make the required changes to the plugin, so it support NS 6+ and submit a PR which I will happily merge and publish on NPM, so all the community can benefit from it 😉

**Comment by aaayushsingh** [comment]
@razorsyntax I created [this](https://github.com/aaayushsingh/NativeScript-Grid-View) fork based on [this](https://github.com/PeterStaev/NativeScript-Grid-View/issues/59#issuecomment-513577050) comment in [this issue](https://github.com/PeterStaev/NativeScript-Grid-View/issues/59).

It is not perfect but it works. You can directly add it using `tns plugin add https://github.com/aaayushsingh/NativeScript-Grid-View`

I wont't submit a PR here yet because I did the .d.ts file in a hurry and replaced everything there and I'm not sure if it'll work
